name: tf-checks

on:
  pull_request:
  workflow_dispatch:

jobs:
# Update 'Job name' and 'working_directory' as needed based on the module structure.
  private_pqsql_vnet_integration-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/private_pqsql_vnet_integration/'
      provider: none

  private_pqsql_private_endpoint-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/private_pqsql_with_private_endpoint/'
      provider: none

  public_pqsql_basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/public_pqsql_basic/'
      provider: none

# Seperate Job for TFlint workflow call
  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-lint.yml@v2
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
